zookeeper0:
  container_name: "zookeeper0"
  image: jplock/zookeeper:3.4.6
  ports: 
    - "2181:2181"

zookeeper1:
  container_name: "zookeeper1"
  image: jplock/zookeeper:3.4.6
  ports: 
    - "2182:2181"

zoofence:
  container_name: "zoofence"
  build: .
